#include <iostream>
#include <cstdlib>
#include <math.h>
/* transacciones en un cajero */ 
using namespace std;
int main(int argc, char** argv) {
	system("color f0");
	int opcion;
	float clave,valor,cuenta,agua,luz,gas,telefonia,consignar,retirar,otro,dinerc,pc,a,b;
	char respuesta;
	cout<<endl<<endl;
	cout<<"\t\t ingrese su numero de cuenta 6 digitos "<<endl;
	cin>>cuenta;
	if(cuenta>=100000&&cuenta<=999999)
	{cout<<"\t\t ingrese su clave 4 digitos "<<endl;
	cin>>clave;
	if(clave>=1000&&clave<=9999)
    { cout<<"\t\t같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같"<<endl;
      cout<<"\t\t                  ingrese el dinero en la cuenta                  "<<endl;
      cout<<"\t\t같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같"<<endl;
      cin>>dinerc;                                                   
	do{system("cls");
    cout<<"\t\t같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같"<<endl;
    cout<<"\t\t                  biemvenido al banco DMV                         "<<endl;
    cout<<"\t\t                      su banco amigo                              "<<endl;
    cout<<"\t\t                     digite su opcion                             "<<endl;
	cout<<"\t\t                       1.Consignar                                "<<endl;
	cout<<"\t\t                       2.Retiro                                   "<<endl;
	cout<<"\t\t                       3.Pago de servicios                        "<<endl;
	cout<<"\t\t                       4.Cambio de clave                          "<<endl;
    cout<<"\t\t같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같"<<endl;
    cout<<"\t\t       ingrese en numero de su opcion      "<<endl;
    cin>>opcion;
    system("cls");
    switch(opcion){
    case 1:cout<<"\t\t같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같"<<endl;
    cout<<"\t\t                            1.10,000$                                             "<<endl;
    cout<<"\t\t                            2.50,000$                                               "<<endl;
    cout<<"\t\t                            3.90,000$                                                "<<endl;
	cout<<"\t\t                            4.100,000$                                                "<<endl;
	cout<<"\t\t                            5.200,000$                                                "<<endl;
	cout<<"\t\t                            6.400,000$                                                "<<endl;
	cout<<"\t\t                            7.otro$                                                "<<endl;
    cout<<"\t\t같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같"<<endl;
    cout<<"\t\t       ingrese en numero de su opcion      "<<endl;
    cin>>opcion;
    system("cls");
    switch(opcion){
	 
	 case 1: cout<<"\t\t                      cosignacion                                         "<<endl;
	         cout<<"\t\t                       1.10,000$                                          "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	         pc=valor-10000;
	         consignar=dinerc+10000;
	         cout<<"\t\t la cosignacion se ha efectuado su saldo es   "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<consignar<<endl;
	         dinerc=consignar;
	         system("pause"); 
			 break; 
	case 2: cout<<"\t\t                      cosignacion                                         "<<endl;
	         cout<<"\t\t                      2.50,000$                                           "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	         pc=valor-50000;
	         consignar=dinerc+50000;
	         cout<<"\t\t la cosignacion se ha efectuado su saldo es   "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<consignar<<endl;
	         dinerc=consignar;
	         system("pause"); 
			 break; 
	case 3: cout<<"\t\t                      cosignacion                                         "<<endl;
	         cout<<"\t\t                      3.90,000$                                            "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	         pc=valor-90000;
	         consignar=dinerc+90000;
	         cout<<"\t\t la cosignacion se ha efectuado su saldo es   "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<consignar<<endl;
	         dinerc=consignar;
	         system("pause"); 
			 break; 
	case 4: cout<<"\t\t                      cosignacion                                         "<<endl;
	         cout<<"\t\t                     4.100,000$                                            "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	         pc=valor-100000;
	         consignar=dinerc+100000;
	         cout<<"\t\t la cosignacion se ha efectuado su saldo es   "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<consignar<<endl;
	         dinerc=consignar;
	         system("pause"); 
			 break;
	case 5: cout<<"\t\t                      cosignacion                                         "<<endl;
	         cout<<"\t\t                     5.200,000$                                            "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	         pc=valor-200000;
	         consignar=dinerc+200000;
	         cout<<"\t\t la cosignacion se ha efectuado su saldo es   "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<consignar<<endl;
	         dinerc=consignar;
	         system("pause"); 
			 break;  
	case 6: cout<<"\t\t                      cosignacion                                         "<<endl;
	         cout<<"\t\t                     6.400,000$                                            "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	         pc=valor-400000;
	         consignar=dinerc+400000;
	         cout<<"\t\t la cosignacion se ha efectuado su saldo es   "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<consignar<<endl;
	         dinerc=consignar;
	         system("pause"); 
			 break;
	case 7: cout<<"\t\t                        cosignacion                                           "<<endl;
	         cout<<"\t\t                         otro$                                            "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	         cout<<"\t\t              ingrese la sifra que quiere retirar                                "<<endl;
	         cin>>otro;
	         pc=valor-otro;
	         consignar=dinerc+otro;
	         cout<<"\t\t el cosignacion se ha efectuado su saldo es  "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<consignar<<endl;
	        dinerc=consignar;
	         system("pause"); 
			 break;}
			system("pause"); 
			break; 
case 2:cout<<"\t\t같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같"<<endl;
    cout<<"\t\t                            1.10,000$                                             "<<endl;
    cout<<"\t\t                            2.50,000$                                               "<<endl;
    cout<<"\t\t                            3.90,000$                                                "<<endl;
	cout<<"\t\t                            4.100,000$                                                "<<endl;
	cout<<"\t\t                            5.200,000$                                                "<<endl;
	cout<<"\t\t                            6.400,000$                                                "<<endl;
	cout<<"\t\t                            7.otro$                                                "<<endl;
    cout<<"\t\t같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같"<<endl;
    cout<<"\t\t       ingrese en numero de su opcion      "<<endl;
    cin>>opcion;
    system("cls");
    switch(opcion){
	 
	 case 1: cout<<"\t\t                         retiro                                         "<<endl;
	         cout<<"\t\t                       1.10,000$                                          "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	         pc=valor+10000;
	         retirar=dinerc-10000;
	         cout<<"\t\t el retiro se ha efectuado su saldo es   "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<retirar<<endl;
	         dinerc=retirar;
	         system("pause"); 
			 break; 
	case 2: cout<<"\t\t                         retiro                                           "<<endl;
	         cout<<"\t\t                      2.50,000$                                           "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	         pc=valor+50000;
	         retirar=dinerc-50000;
	         cout<<"\t\t el retiro se ha efectuado su saldo es   "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<retirar<<endl;
	        dinerc=retirar;
	         system("pause"); 
			 break; 
	case 3: cout<<"\t\t                         retiro                                          "<<endl;
	         cout<<"\t\t                      3.90,000$                                            "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	         pc=valor+90000;
	         retirar=dinerc-90000;
	         cout<<"\t\t el retiro se ha efectuado su saldo es   "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<retirar<<endl;
	        dinerc=retirar;
	         system("pause"); 
			 break; 
	case 4: cout<<"\t\t                        retiro                                           "<<endl;
	         cout<<"\t\t                     4.100,000$                                            "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	        pc=valor+100000;
	         retirar=dinerc-100000;
	         cout<<"\t\t el retiro se ha efectuado su saldo es   "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<retirar<<endl;
	        dinerc=retirar;
	         system("pause"); 
			 break;
	case 5: cout<<"\t\t                        retiro                                           "<<endl;
	         cout<<"\t\t                     5.200,000$                                            "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	        pc=valor+200000;
	         retirar=dinerc-200000;
	         cout<<"\t\t el retiro se ha efectuado su saldo es  "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<retirar<<endl;
	        dinerc=retirar;
	         system("pause"); 
			 break;  
	case 6: cout<<"\t\t                        retiro                                           "<<endl;
	         cout<<"\t\t                     6.400,000$                                            "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	        pc=valor+400000;
	         retirar=dinerc-400000;
	         cout<<"\t\t el retiro se ha efectuado su saldo es  "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<retirar<<endl;
	        dinerc=retirar;
	         system("pause"); 
			 break;
	case 7: cout<<"\t\t                        retiro                                           "<<endl;
	         cout<<"\t\t                        otro$                                            "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	         cout<<"\t\t              ingrese la sifra que quiere retirar                                "<<endl;
	         cin>>otro;
	         pc=valor+otro;
	         retirar=dinerc-otro;
	         cout<<"\t\t el retiro se ha efectuado su saldo es  "<<pc<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<retirar<<endl;
	        dinerc=retirar;
	         system("pause"); 
			 break;}
			system("pause"); 
			break; 
case 3:cout<<"\t\t같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같"<<endl;
    cout<<"\t\t                            1.agua                                           "<<endl;
    cout<<"\t\t                            2.luz                                              "<<endl;
    cout<<"\t\t                            3.gas                                                "<<endl;
	cout<<"\t\t                            4.telefonia                                                "<<endl;
    cout<<"\t\t같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같같"<<endl;
    cout<<"\t\t       ingrese en numero de su opcion      "<<endl;
    cin>>opcion;
    system("cls");
    switch(opcion){
	 
	 case 1: cout<<"\t\t                         1.agua                                         "<<endl;
	         cout<<"\t\t                  ingrese valor del recibo                               "<<endl;
	         cin>>valor;
	         agua=dinerc-valor;
	         cout<<"\t\t el retiro se ha efectuado su saldo es   "<<valor<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<agua<<endl;
	         dinerc=agua;
	         system("pause"); 
			 break; 
	case 2: cout<<"\t\t                         2.luz                                           "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	         cin>>valor;
	         luz=dinerc-valor;
	         cout<<"\t\t el retiro se ha efectuado su saldo es   "<<valor<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<luz<<endl;
	         dinerc=luz;
	         system("pause"); 
			 break; 
	case 3: cout<<"\t\t                         3.gas                                         "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	        cin>>valor;
	         gas=dinerc-valor;
	         cout<<"\t\t el retiro se ha efectuado su saldo es   "<<valor<<endl;
	         cout<<"\t\t el dinero en la cuenta es   "<<gas<<endl;
	         dinerc=gas;
	         system("pause"); 
			 break; 
	case 4: cout<<"\t\t                     4.telefonia                                           "<<endl;
	         cout<<"\t\t                  ingrese dinero disponible                               "<<endl;
	        cin>>valor;
	        telefonia=dinerc-valor;
	        cout<<"\t\t el retiro se ha efectuado su saldo es   "<<valor<<endl;
	        cout<<"\t\t el dinero en la cuenta es   "<<telefonia<<endl;
	        dinerc=telefonia;
	        system("pause"); 
		    break;}
			system("pause"); 
			break; 
case 4:cout<<"cambiar clave"<<endl;
       cout<<"la clave actual es "<<clave<<endl;
       clave=a;
       cout<<"ingrese la nueva clave "<<endl;
       cin>>b;
       clave=b;
	   cout<<"la clave nueva es "<<clave<<endl;
	   system("pause"); 
	   break; 
	
default :cout<<"\t\t    no exite ese comando   "<<endl;}		
			
cout<<" quiere realizar otra transacion  s/n ? ";
cin>>respuesta;

}while(respuesta == 's');	

system("pause"); 
return 0;
}else{cout<<"la clave no valida"<<endl;}
}else{cout<<"la cuenta no valida"<<endl;}
}
